version: 0.2

phases:
  build:
    commands:
      # 1. Backend-a package pannu
      - echo "Packaging backend..."
      - aws cloudformation package \
          --template-file template.yaml \
          --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-zxg34ej7v7wy \
          --output-template-file packaged-template.yaml
          
      # 2. Frontend files-a oru thani folder-la podu
      - echo "Copying frontend files..."
      - mkdir frontend-output
      - cp frontend/index.html frontend-output/

artifacts:
  files:
    - packaged-template.yaml
  secondary-artifacts:
    FrontendArtifact:
      files:
        - '**/*'
      base-directory: 'frontend-output'