AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A serverless To-Do application with CRUD operations

Globals:
  Function:
    Timeout: 10
  Api:
    Cors: # Enable CORS for all methods
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  TodoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  TodoApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: app.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable
      Policies:
        - DynamoDBCrudPolicy: # Give full CRUD permissions
            TableName: !Ref TodoTable
      Events:
        # GET /todos - List all items
        ListItems:
          Type: Api
          Properties:
            Path: /todos
            Method: GET
        # POST /todos - Add new item
        AddItem:
          Type: Api
          Properties:
            Path: /todos
            Method: POST
        # DELETE /todos/{id} - Delete specific item
        DeleteItem:
          Type: Api
          Properties:
            Path: /todos/{id} # Note the {id} here
            Method: DELETE
        # PUT /todos/{id} - Update specific item
        UpdateItem:
          Type: Api
          Properties:
            Path: /todos/{id} # Note the {id} here
            Method: PUT

Outputs:
  TodoApiUrl:
    Description: "API Gateway endpoint URL for listing/adding todos"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos"